"""6 migrations

Revision ID: 9321e00ffdc9
Revises: a74f30a014c0
Create Date: 2024-12-06 11:39:59.991101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9321e00ffdc9'
down_revision = 'a74f30a014c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_constraint('grade_subject_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('grade_teacher_id_fkey', type_='foreignkey')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('date')
        batch_op.drop_column('status')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('grade_teacher_id_fkey', 'user', ['teacher_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('grade_subject_id_fkey', 'subject', ['subject_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
