name: Flask Application

on:
  push:
    branches:
      - first_branch
  pull_request:
    branches:
      - first_branch

jobs:
  lint-and-syntax-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8  # Установка flake8 для проверки стиля кода

    - name: Run syntax check
      run: python -m py_compile $(find . -name "*.py")

    - name: Run flake8 (style check)
      run: flake8 . --count --max-line-length=79 --show-source --statistics
